# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vehicle_position.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vehicle_position.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16vehicle_position.proto\"\xf5\x04\n\x0fVehiclePosition\x12\x11\n\tentity_id\x18\x01 \x01(\t\x12\x16\n\x0e\x66\x65\x65\x64_timestamp\x18\x02 \x01(\x03\x12\x1d\n\x15gtfs_realtime_version\x18\x03 \x01(\t\x12\x16\n\x0eincrementality\x18\x04 \x01(\t\x12\x0f\n\x07trip_id\x18\x05 \x01(\t\x12\x10\n\x08route_id\x18\x06 \x01(\t\x12\x14\n\x0c\x64irection_id\x18\x07 \x01(\x05\x12\x12\n\nstart_time\x18\x08 \x01(\t\x12\x12\n\nstart_date\x18\t \x01(\t\x12\x1d\n\x15schedule_relationship\x18\n \x01(\t\x12\x12\n\nvehicle_id\x18\x0b \x01(\t\x12\x15\n\rvehicle_label\x18\x0c \x01(\t\x12\x15\n\rlicense_plate\x18\r \x01(\t\x12\x1d\n\x15wheelchair_accessible\x18\x0e \x01(\t\x12\x10\n\x08latitude\x18\x0f \x01(\x02\x12\x11\n\tlongitude\x18\x10 \x01(\x02\x12\x0f\n\x07\x62\x65\x61ring\x18\x11 \x01(\x02\x12\x10\n\x08odometer\x18\x12 \x01(\x01\x12\r\n\x05speed\x18\x13 \x01(\x02\x12\x1d\n\x15\x63urrent_stop_sequence\x18\x14 \x01(\x05\x12\x0f\n\x07stop_id\x18\x15 \x01(\t\x12\x16\n\x0e\x63urrent_status\x18\x16 \x01(\t\x12\x19\n\x11vehicle_timestamp\x18\x17 \x01(\x03\x12\x18\n\x10\x63ongestion_level\x18\x18 \x01(\t\x12\x18\n\x10occupancy_status\x18\x19 \x01(\t\x12\x1c\n\x14occupancy_percentage\x18\x1a \x01(\x05\x12\x13\n\x0bingested_at\x18\x1b \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vehicle_position_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VEHICLEPOSITION']._serialized_start=27
  _globals['_VEHICLEPOSITION']._serialized_end=656
# @@protoc_insertion_point(module_scope)
